# Form implementation generated from reading ui file 'InterfaceSelectDialogView_pre.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_InterfaceSelectDialog(object):
    def setupUi(self, InterfaceSelectDialog):
        InterfaceSelectDialog.setObjectName("InterfaceSelectDialog")
        InterfaceSelectDialog.resize(710, 467)
        self.minButton = QtWidgets.QPushButton(parent=InterfaceSelectDialog)
        self.minButton.setGeometry(QtCore.QRect(620, 10, 31, 31))
        self.minButton.setText("")
        self.minButton.setObjectName("minButton")
        self.closeButton = QtWidgets.QPushButton(parent=InterfaceSelectDialog)
        self.closeButton.setGeometry(QtCore.QRect(660, 10, 31, 31))
        self.closeButton.setText("")
        self.closeButton.setObjectName("closeButton")
        self.label = QtWidgets.QLabel(parent=InterfaceSelectDialog)
        self.label.setGeometry(QtCore.QRect(10, 50, 141, 41))
        self.label.setStyleSheet("font: 17pt \"Microsoft YaHei UI\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=InterfaceSelectDialog)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 211, 16))
        self.label_2.setStyleSheet("font: 10pt \"Microsoft YaHei UI\";")
        self.label_2.setObjectName("label_2")
        self.textBrowser = QtWidgets.QTextBrowser(parent=InterfaceSelectDialog)
        self.textBrowser.setGeometry(QtCore.QRect(10, 120, 691, 341))
        self.textBrowser.setObjectName("textBrowser")
        self.listWidget = QtWidgets.QListWidget(parent=InterfaceSelectDialog)
        self.listWidget.setGeometry(QtCore.QRect(20, 130, 671, 321))
        self.listWidget.setObjectName("listWidget")
        self.ucasLabel = QtWidgets.QLabel(parent=InterfaceSelectDialog)
        self.ucasLabel.setGeometry(QtCore.QRect(10, 10, 41, 41))
        self.ucasLabel.setText("")
        self.ucasLabel.setObjectName("ucasLabel")
        self.ucasLabel.raise_()
        self.minButton.raise_()
        self.closeButton.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.textBrowser.raise_()
        self.listWidget.raise_()

        self.retranslateUi(InterfaceSelectDialog)
        QtCore.QMetaObject.connectSlotsByName(InterfaceSelectDialog)

    def retranslateUi(self, InterfaceSelectDialog):
        _translate = QtCore.QCoreApplication.translate
        InterfaceSelectDialog.setWindowTitle(_translate("InterfaceSelectDialog", "Dialog"))
        self.label.setText(_translate("InterfaceSelectDialog", "捕获"))
        self.label_2.setText(_translate("InterfaceSelectDialog", "显示所有网络适配器"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    InterfaceSelectDialog = QtWidgets.QDialog()
    ui = Ui_InterfaceSelectDialog()
    ui.setupUi(InterfaceSelectDialog)
    InterfaceSelectDialog.show()
    sys.exit(app.exec())
